### PR TITLE
Added enchant.js version of Breakout

### PR DESCRIPTION
**Pull request by MaciejKus**
Hi,
This is a working version of Breakout using enchant.js.

### CODE REVIEW

**Comment by ellisonleao** [comment]
thanks @MaciejKus !!

**Comment by ellisonleao** [comment]
I believe there is an issue on Chrome. When i start the game i get

```
enchant.js:5661 Uncaught InvalidAccessError: Failed to execute 'disconnect' on 'AudioNode': the given destination is not connected.
```
http://www.jsbreakouts.org/enchantjs/index.html

@MaciejKus  can you take a look at that, please ?

**Comment by MaciejKus** [comment]
Hmm, looks like I was testing with an older version of Chrome. It is an issue with the game engine itself, enchant.js. I fixed the issue by making a change on a single line of the game engines code. 

I will go ahead and create a pull request to try to get the enchant.js folks to update their code. Looks like someone already pointed it out:
https://github.com/wise9/enchant.js/issues/312

**Comment by ellisonleao** [comment]
Sure, when its ready please let us know.

**Comment by city41** [comment]
Thanks @ellisonleao, you beat me to it again :) and Thanks @MaciejKus for the enchant.js version, very awesome!

**Comment by ellisonleao** [comment]
Always a pleasure @city41  !

**Pull request merged**
