### PR TITLE
Breakout game implemented with Entropy framework

### PR DESCRIPTION
**Pull request by RainPhilosopher**

### CODE REVIEW

**Comment by ellisonleao** [comment]
Nice, i will add this to the `gh-pages` branch as well. Thanks! :beers:

**Comment by RainPhilosopher** [comment]
Pleasure is all mine.

**Comment by ellisonleao** [comment]
@city41 i've made some changes on `gh-pages` branch, but it still needs to recreate the featureComparison grid. Can you do that? i've updated the grid json file already.

**Comment by city41** [comment]
Thanks @ellisonleao do you want to tweet about Entropy as well? I can if not.

As for featureComparison, it isn't linked to from the main page anymore. Which I completely forgot about. I was thinking of recreating it out of React and make it simpler and easier to update.

So for now, I vote we don't worry about featureComparison. It's just yet one more thing todo in Breakouts :)

**Pull request merged**
